-- DDL gerada a partir de data/ancine/salaexibicao.parquet (6,404 linhas)
CREATE TABLE salaexibicao (
    "NOME_SALA"                      VARCHAR,
    "REGISTRO_SALA"                  BIGINT,
    "CNPJ_SALA"                      VARCHAR,
    "SITUACAO_SALA"                  VARCHAR,
    "DATA_SITUACAO_SALA"             DATE,
    "DATA_INICIO_FUNCIONAMENTO_SALA" DATE,
    "ASSENTOS_SALA"                  BIGINT,
    "ASSENTOS_CADEIRANTES"           BIGINT,
    "ASSENTOS_MOBILIDADE_REDUZIDA"   BIGINT,
    "ASSENTOS_OBESIDADE"             BIGINT,
    "ACESSO_ASSENTOS_COM_RAMPA"      VARCHAR,
    "ACESSO_SALA_COM_RAMPA"          VARCHAR,
    "BANHEIROS_ACESSIVEIS"           VARCHAR,
    "NOME_COMPLEXO"                  VARCHAR,
    "REGISTRO_COMPLEXO"              BIGINT,
    "SITUACAO_COMPLEXO"              VARCHAR,
    "DATA_SITUACAO_COMPLEXO"         DATE,
    "PAGINA_ELETRONICA_COMPLEXO"     VARCHAR,
    "ENDERECO_COMPLEXO"              VARCHAR,
    "NUMERO_ENDERECO_COMPLEXO"       VARCHAR,
    "COMPLEMENTO_COMPLEXO"           VARCHAR,
    "BAIRRO_COMPLEXO"                VARCHAR,
    "MUNICIPIO_COMPLEXO"             VARCHAR,
    "CEP_COMPLEXO"                   VARCHAR,
    "UF_COMPLEXO"                    VARCHAR,
    "COMPLEXO_ITINERANTE"            VARCHAR,
    "OPERACAO_USUAL"                 VARCHAR,
    "NOME_EXIBIDOR"                  VARCHAR,
    "REGISTRO_EXIBIDOR"              BIGINT,
    "CNPJ_EXIBIDOR"                  VARCHAR,
    "SITUACAO_EXIBIDOR"              VARCHAR,
    "NOME_GRUPO_EXIBIDOR"            VARCHAR
);
